### ISSUE TITLE
[Admin] Mail aux admins lorsqu'un compte à valider est crée

### ISSUE THREAD

**Issue by anakin-datawalker** [louity/challenge#15]
Il serait utile qu'un mail soit envoyé aux admins par le biais de l'adresse challengedata@ens.fr pour prévenir qu'un compte à valider (professeurs, challenges providers) a été créé.

**Comment by louity** [comment]
La logique est codee, mais pour l'instant j'ai mis mon email puisque j'ai pas acces a l'email challengedata att ens.fr , il suffit de changer un fichier de config pour ca
