### ISSUE TITLE
[participant] Challenge visible mais non inscrit : lien de téléchargement cassé

### ISSUE THREAD

**Issue by AndreuxMath** [louity/challenge#2]
En tant que participant, il est possible de voir tous les challenges actuellement actifs depuis `/challenges`. Sur leur page, quand on n'est pas inscrit, il est quand même possible de cliquer sur le lien de téléchargement des données. On obtient alors une erreur 404 : 

**_Page not found (404)_**

**Request Method**: GET
**Request URL**: http://challengedata2.ens.fr/participants/challenges/2/download/x-train
participants.views.challenge_download_file.challenge_download_file
**Raised by**: participants.views.challenge_download_file.challenge_download_file

Not registered to the challenge

You're seeing this error because you have `DEBUG = True` in your Django settings file. Change that to `False`, and Django will display a standard 404 page.

**Comment by louity** [comment]
Resolu
