### ISSUE TITLE
Impossible de télécharger un dataset

### ISSUE THREAD

**Issue by Jonas1312** [louity/challenge#25]
Bonjour,

Il m'est actuellement impossible de télécharger le dataset `x_train` du challenge 18 https://challengedata.ens.fr/participants/challenges/18/ car le téléchargement coupe systématiquement.

J'ai testé sur plusieurs réseaux, plusieurs ordinateurs, plusieurs méthodes de téléchargement (firefox, edge, wget, curl) et dans tous les cas il est impossible de reprendre le téléchargement après une interruption, curl affiche avec l'argument `-C` : 

> “Curl : (33) HTTP server doesn't seem to support byte ranges. Cannot resume.”

Est-ce qu'il serait possible de régler ce bug côté serveur ou de mettre à disposition d'autres manières de téléchargement (ftp, torrent, split en plusieurs fichiers), merci

**Comment by louity** [comment]
Merci, j'ai change la logique de telechargement des fichiers pour les servir avec [nginx x-accell](https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/) , ce qui j'espere va regler le probleme.

**Comment by Jonas1312** [comment]
ça a marché du premier coup de mon côté, merci !
