### ISSUE TITLE
[participant] Champs manquants lors de l'inscription

### ISSUE THREAD

**Issue by anakin-datawalker** [louity/challenge#3]
Il manque les champs suivants à la page d'inscription en tant que participant (cf. p. 6/7 des specs) :

- Nom
- Prénom
- Réponse (Oui/Non) à la question: “Do you agree to be contacted by challenge
providers?” 
- Statut (4 possibles : student, researcher/professor, data scientist and other)
- Institution/company (si possible rajouter une bulle d'information à côté de ce champ contenant les détails suivantes : "university for student and researcher/professor, company for data scientist, and anything for other")

**Comment by louity** [comment]
Resolu, pas de nom-prenom pour faciliter la RGPD compliance
