### ISSUE TITLE
[Admin] Dissocier pending de actifs

### ISSUE THREAD

**Issue by anakin-datawalker** [louity/challenge#8]
Est ce possible de dissocier les pending providers / challenges / etc. des providers / challenges / etc. activés : au sein des providers / challenges / etc. apparaissent à la fois pour le moment les providers / challenges / etc. activés mais également les pending.

**Comment by louity** [comment]
J'ai ajoute un classe approved challenge. L'interface Challenge doit rester parce que c'est via celle la que les providers voient leur challenges
